package com.soundless

import androidx.compose.runtime.compositionLocalOf

enum class Language(val code: String, val label: String, val shortLabel: String) {
    EN("en", "English", "EN"),
    KO("ko", "한국어", "한"),
    JA("ja", "日本語", "日"),
    AR("ar", "العربية", "عر"),
    ZH_CN("zh_CN", "简体中文", "简"),
    ZH_TW("zh_TW", "繁體中文", "繁"),
}

val LocalStrings = compositionLocalOf { koreanStrings() }
val LocalLanguage = compositionLocalOf { Language.KO }

fun Language.toStrings(): Strings = when (this) {
    Language.EN -> englishStrings()
    Language.KO -> koreanStrings()
    Language.JA -> japaneseStrings()
    Language.AR -> arabicStrings()
    Language.ZH_CN -> simplifiedChineseStrings()
    Language.ZH_TW -> traditionalChineseStrings()
}

data class Strings(
    val subtitle: String,
    val connectingChecking: String,
    val wirelessDebugSetup: String,
    val splitScreenHint: String,
    val step1Label: String,
    val connectPortLabel: String,
    val connectPortPlaceholder: String,
    val step2Label: String,
    val pairingPortLabel: String,
    val pairingPortPlaceholder: String,
    val pairingCodeLabel: String,
    val pairingCodePlaceholder: String,
    val pairAndConnect: String,
    val pairingFooter: String,
    val shutterOff: String,
    val shutterOn: String,
    val shutterOffDesc: String,
    val shutterOnDesc: String,
    val turnOnShutter: String,
    val turnOffShutter: String,
    val mainFooter: String,
    val errorTitle: String,
    val retry: String,
    // ViewModel messages
    val msgStartingAdb: String,
    val msgEnterPairingInfo: String,
    val msgPairing: String,
    val msgPairingSuccess: String,
    val msgPairingFailed: (String?) -> String,
    val msgEnterDebugPort: String,
    val msgConnecting: String,
    val msgConnectFailed: (String?) -> String,
    val msgDeviceNotFound: String,
    val msgNotSupported: String,
    val msgCannotReadShutter: (String) -> String,
    val msgSettingChangeFailed: (String?) -> String,
    val msgPairingTimeout: String,
    // Onboarding
    val onboardingSubtitle: String,
    val previous: String,
    val next: String,
    val getStarted: String,
    val onboardingStep1Title: String,
    val onboardingStep1Items: List<String>,
    val onboardingStep2Title: String,
    val onboardingStep2Items: List<String>,
    val onboardingStep3Title: String,
    val onboardingStep3Items: List<String>,
    val onboardingStep4Title: String,
    val onboardingStep4Items: List<String>,
    val onboardingStep5Title: String,
    val onboardingStep5Items: List<String>,
)

private fun koreanStrings() = Strings(
    subtitle = "카메라 셔터음 제어",
    connectingChecking = "연결 확인 중...",
    wirelessDebugSetup = "무선 디버깅 설정",
    splitScreenHint = "분할 화면으로 설정과 이 앱을 동시에 열어주세요.",
    step1Label = "Step 1. 무선 디버깅 화면 상단의 포트",
    connectPortLabel = "연결 포트",
    connectPortPlaceholder = "예: 44689",
    step2Label = "Step 2. '페어링 코드로 기기 페어링' 클릭 후\n팝업에 표시된 포트와 코드를 입력",
    pairingPortLabel = "페어링 팝업의 포트",
    pairingPortPlaceholder = "예: 37123 (44689와 다른 번호!)",
    pairingCodeLabel = "페어링 코드 (6자리)",
    pairingCodePlaceholder = "예: 482956",
    pairAndConnect = "페어링 및 연결",
    pairingFooter = "ADB 디버깅을 사용하여 시스템 설정을 변경합니다.\nPC 연결 없이 기기 내에서 직접 동작합니다.",
    shutterOff = "셔터음 꺼짐",
    shutterOn = "셔터음 켜짐",
    shutterOffDesc = "카메라 셔터음이 비활성화되어 있습니다",
    shutterOnDesc = "카메라 셔터음이 활성화되어 있습니다",
    turnOnShutter = "셔터음 켜기",
    turnOffShutter = "셔터음 끄기",
    mainFooter = "로컬 ADB를 사용하여 시스템 설정을 변경합니다.\nPC나 USB 연결 없이 바로 적용됩니다.",
    errorTitle = "오류",
    retry = "다시 시도",
    msgStartingAdb = "ADB 서버 시작 중...",
    msgEnterPairingInfo = "페어링 포트와 코드를 입력해주세요",
    msgPairing = "페어링 중...",
    msgPairingSuccess = "페어링 성공! 연결 중...",
    msgPairingFailed = { e -> "페어링 실패: ${e ?: "알 수 없는 오류"}" },
    msgEnterDebugPort = "무선 디버깅 포트를 입력해주세요",
    msgConnecting = "연결 중...",
    msgConnectFailed = { e -> "연결 실패: ${e ?: "장치를 찾을 수 없습니다"}" },
    msgDeviceNotFound = "장치를 찾을 수 없습니다",
    msgNotSupported = "이 기기는 셔터음 설정을 지원하지 않습니다.\n삼성 갤럭시 한국 출시 기기에서만 사용 가능합니다.",
    msgCannotReadShutter = { e -> "셔터음 상태를 읽을 수 없습니다: $e" },
    msgSettingChangeFailed = { e -> "설정 변경 실패: ${e ?: ""}" },
    msgPairingTimeout = "페어링 시간 초과",
    onboardingSubtitle = "설정 가이드",
    previous = "이전",
    next = "다음",
    getStarted = "시작하기",
    onboardingStep1Title = "개발자 옵션 활성화",
    onboardingStep1Items = listOf(
        "설정 > 휴대전화 정보 > 소프트웨어 정보로 이동",
        "'빌드 번호'를 7번 연속 탭하세요",
        "\"개발자 모드가 활성화되었습니다\" 메시지가 나타납니다",
        "설정 메인 화면으로 돌아가면 하단에 '개발자 옵션'이 추가됩니다",
    ),
    onboardingStep2Title = "USB 디버깅 켜기",
    onboardingStep2Items = listOf(
        "설정 > 개발자 옵션으로 이동",
        "'USB 디버깅'을 켜주세요",
        "USB 디버깅이 회색이면:\n  설정 > 보안 및 개인정보 > 자동 차단기를\n  꺼주세요 (삼성 기기)",
    ),
    onboardingStep3Title = "무선 디버깅 켜기",
    onboardingStep3Items = listOf(
        "설정 > 개발자 옵션 > 무선 디버깅으로 이동",
        "무선 디버깅을 켜주세요",
        "Wi-Fi에 연결되어 있어야 합니다",
        "화면 상단에 표시되는 포트 번호를 기억해주세요\n  (예: 172.30.1.22:44689 에서 44689)",
    ),
    onboardingStep4Title = "페어링 하기",
    onboardingStep4Items = listOf(
        "중요: 분할 화면으로 설정과 이 앱을\n동시에 열어주세요!",
        "설정에서 '페어링 코드로 기기 페어링'을 탭",
        "팝업에 나타나는 3가지를 앱에 입력:\n  ① 연결 포트: 무선 디버깅 화면의 포트\n     (예: 44689)\n  ② 페어링 포트: 팝업의 포트\n     (예: 43641, 연결 포트와 다름!)\n  ③ 페어링 코드: 팝업의 6자리 숫자",
        "팝업을 닫지 마세요! 입력 후 바로\n'페어링 및 연결' 버튼을 탭하세요",
    ),
    onboardingStep5Title = "셔터음 끄기",
    onboardingStep5Items = listOf(
        "연결이 완료되면 셔터음 제어 화면이 나타납니다",
        "버튼 하나로 셔터음을 켜고 끌 수 있습니다",
        "기본 카메라 앱에 바로 적용됩니다",
        "PC나 USB 케이블이 필요 없습니다!",
    ),
)

private fun englishStrings() = Strings(
    subtitle = "Camera Shutter Sound Control",
    connectingChecking = "Checking connection...",
    wirelessDebugSetup = "Wireless Debugging Setup",
    splitScreenHint = "Open Settings and this app side by side using split screen.",
    step1Label = "Step 1. Port from Wireless Debugging screen",
    connectPortLabel = "Connection Port",
    connectPortPlaceholder = "e.g., 44689",
    step2Label = "Step 2. Tap 'Pair device with pairing code'\nand enter the port & code from the popup",
    pairingPortLabel = "Pairing popup port",
    pairingPortPlaceholder = "e.g., 37123 (different from above!)",
    pairingCodeLabel = "Pairing code (6 digits)",
    pairingCodePlaceholder = "e.g., 482956",
    pairAndConnect = "Pair & Connect",
    pairingFooter = "Uses ADB debugging to change system settings.\nWorks directly on device without a PC.",
    shutterOff = "Shutter Sound Off",
    shutterOn = "Shutter Sound On",
    shutterOffDesc = "Camera shutter sound is disabled",
    shutterOnDesc = "Camera shutter sound is enabled",
    turnOnShutter = "Turn On Shutter Sound",
    turnOffShutter = "Turn Off Shutter Sound",
    mainFooter = "Changes system settings using local ADB.\nNo PC or USB connection required.",
    errorTitle = "Error",
    retry = "Retry",
    msgStartingAdb = "Starting ADB server...",
    msgEnterPairingInfo = "Please enter pairing port and code",
    msgPairing = "Pairing...",
    msgPairingSuccess = "Paired! Connecting...",
    msgPairingFailed = { e -> "Pairing failed: ${e ?: "Unknown error"}" },
    msgEnterDebugPort = "Please enter wireless debugging port",
    msgConnecting = "Connecting...",
    msgConnectFailed = { e -> "Connection failed: ${e ?: "Device not found"}" },
    msgDeviceNotFound = "Device not found",
    msgNotSupported = "This device does not support shutter sound settings.\nOnly available on Samsung Galaxy devices sold in Korea.",
    msgCannotReadShutter = { e -> "Cannot read shutter sound state: $e" },
    msgSettingChangeFailed = { e -> "Failed to change setting: ${e ?: ""}" },
    msgPairingTimeout = "Pairing timed out",
    onboardingSubtitle = "Setup Guide",
    previous = "Previous",
    next = "Next",
    getStarted = "Get Started",
    onboardingStep1Title = "Enable Developer Options",
    onboardingStep1Items = listOf(
        "Go to Settings > About Phone > Software Information",
        "Tap 'Build Number' 7 times in a row",
        "You'll see \"Developer mode has been enabled\"",
        "Go back to Settings — 'Developer Options' will appear at the bottom",
    ),
    onboardingStep2Title = "Turn On USB Debugging",
    onboardingStep2Items = listOf(
        "Go to Settings > Developer Options",
        "Turn on 'USB Debugging'",
        "If USB Debugging is grayed out:\n  Go to Settings > Security & Privacy > Auto Blocker\n  and turn it OFF (Samsung devices)",
    ),
    onboardingStep3Title = "Turn On Wireless Debugging",
    onboardingStep3Items = listOf(
        "Go to Settings > Developer Options > Wireless Debugging",
        "Turn on Wireless Debugging",
        "You must be connected to Wi-Fi",
        "Note the port number shown at the top\n  (e.g., 44689 from 172.30.1.22:44689)",
    ),
    onboardingStep4Title = "Pair Device",
    onboardingStep4Items = listOf(
        "Important: Use split screen to keep Settings\nand this app open at the same time!",
        "Tap 'Pair device with pairing code' in Settings",
        "Enter the 3 values from the popup:\n  ① Connection port: from Wireless Debugging\n     (e.g., 44689)\n  ② Pairing port: from the popup\n     (e.g., 43641, different from above!)\n  ③ Pairing code: 6-digit number from popup",
        "Don't close the popup! Tap 'Pair & Connect'\nimmediately after entering the values",
    ),
    onboardingStep5Title = "Disable Shutter Sound",
    onboardingStep5Items = listOf(
        "Once connected, the shutter sound control screen appears",
        "Toggle the shutter sound on or off with one tap",
        "Changes apply to the default camera app",
        "No PC or USB cable needed!",
    ),
)

private fun japaneseStrings() = Strings(
    subtitle = "カメラシャッター音制御",
    connectingChecking = "接続確認中...",
    wirelessDebugSetup = "ワイヤレスデバッグ設定",
    splitScreenHint = "分割画面で設定とこのアプリを同時に開いてください。",
    step1Label = "Step 1. ワイヤレスデバッグ画面上部のポート",
    connectPortLabel = "接続ポート",
    connectPortPlaceholder = "例: 44689",
    step2Label = "Step 2.「ペア設定コードによるデバイスのペア設定」\nをタップし、ポートとコードを入力",
    pairingPortLabel = "ペアリングポップアップのポート",
    pairingPortPlaceholder = "例: 37123（上記と異なる番号！）",
    pairingCodeLabel = "ペアリングコード（6桁）",
    pairingCodePlaceholder = "例: 482956",
    pairAndConnect = "ペアリング＆接続",
    pairingFooter = "ADBデバッグを使用してシステム設定を変更します。\nPCなしでデバイス上で直接動作します。",
    shutterOff = "シャッター音オフ",
    shutterOn = "シャッター音オン",
    shutterOffDesc = "カメラのシャッター音が無効になっています",
    shutterOnDesc = "カメラのシャッター音が有効になっています",
    turnOnShutter = "シャッター音をオンにする",
    turnOffShutter = "シャッター音をオフにする",
    mainFooter = "ローカルADBを使用してシステム設定を変更します。\nPCやUSB接続は不要です。",
    errorTitle = "エラー",
    retry = "再試行",
    msgStartingAdb = "ADBサーバー起動中...",
    msgEnterPairingInfo = "ペアリングポートとコードを入力してください",
    msgPairing = "ペアリング中...",
    msgPairingSuccess = "ペアリング成功！接続中...",
    msgPairingFailed = { e -> "ペアリング失敗: ${e ?: "不明なエラー"}" },
    msgEnterDebugPort = "ワイヤレスデバッグポートを入力してください",
    msgConnecting = "接続中...",
    msgConnectFailed = { e -> "接続失敗: ${e ?: "デバイスが見つかりません"}" },
    msgDeviceNotFound = "デバイスが見つかりません",
    msgNotSupported = "このデバイスはシャッター音設定に対応していません。\n韓国販売のSamsung Galaxyでのみ使用可能です。",
    msgCannotReadShutter = { e -> "シャッター音の状態を読み取れません: $e" },
    msgSettingChangeFailed = { e -> "設定変更失敗: ${e ?: ""}" },
    msgPairingTimeout = "ペアリングがタイムアウトしました",
    onboardingSubtitle = "セットアップガイド",
    previous = "前へ",
    next = "次へ",
    getStarted = "始める",
    onboardingStep1Title = "開発者オプションを有効化",
    onboardingStep1Items = listOf(
        "設定 > 端末情報 > ソフトウェア情報に移動",
        "「ビルド番号」を7回連続タップ",
        "「開発者モードが有効になりました」と表示されます",
        "設定に戻ると「開発者オプション」が追加されます",
    ),
    onboardingStep2Title = "USBデバッグをオンにする",
    onboardingStep2Items = listOf(
        "設定 > 開発者オプションに移動",
        "「USBデバッグ」をオンにしてください",
        "USBデバッグがグレーの場合:\n  設定 > セキュリティ > 自動ブロッカーを\n  オフにしてください（Samsung端末）",
    ),
    onboardingStep3Title = "ワイヤレスデバッグをオンにする",
    onboardingStep3Items = listOf(
        "設定 > 開発者オプション > ワイヤレスデバッグに移動",
        "ワイヤレスデバッグをオンにしてください",
        "Wi-Fiに接続されている必要があります",
        "画面上部に表示されるポート番号を確認\n  （例: 172.30.1.22:44689 の 44689）",
    ),
    onboardingStep4Title = "ペアリングする",
    onboardingStep4Items = listOf(
        "重要: 分割画面で設定とこのアプリを\n同時に開いてください！",
        "設定で「ペア設定コードによるデバイスのペア設定」をタップ",
        "ポップアップの3つの値をアプリに入力:\n  ① 接続ポート: ワイヤレスデバッグのポート\n     （例: 44689）\n  ② ペアリングポート: ポップアップのポート\n     （例: 43641、接続ポートとは異なる！）\n  ③ ペアリングコード: ポップアップの6桁の数字",
        "ポップアップを閉じないでください！入力後すぐに\n「ペアリング＆接続」をタップしてください",
    ),
    onboardingStep5Title = "シャッター音をオフにする",
    onboardingStep5Items = listOf(
        "接続完了後、シャッター音制御画面が表示されます",
        "ワンタップでシャッター音のオン・オフを切り替え",
        "デフォルトカメラアプリに即座に適用されます",
        "PCやUSBケーブルは不要です！",
    ),
)

private fun arabicStrings() = Strings(
    subtitle = "التحكم في صوت الغالق",
    connectingChecking = "جارٍ التحقق من الاتصال...",
    wirelessDebugSetup = "إعداد التصحيح اللاسلكي",
    splitScreenHint = "افتح الإعدادات وهذا التطبيق جنبًا إلى جنب باستخدام تقسيم الشاشة.",
    step1Label = "الخطوة 1. المنفذ من شاشة التصحيح اللاسلكي",
    connectPortLabel = "منفذ الاتصال",
    connectPortPlaceholder = "مثال: 44689",
    step2Label = "الخطوة 2. انقر على 'إقران الجهاز برمز الإقران'\nوأدخل المنفذ والرمز من النافذة المنبثقة",
    pairingPortLabel = "منفذ نافذة الإقران",
    pairingPortPlaceholder = "مثال: 37123 (مختلف عن أعلاه!)",
    pairingCodeLabel = "رمز الإقران (6 أرقام)",
    pairingCodePlaceholder = "مثال: 482956",
    pairAndConnect = "إقران واتصال",
    pairingFooter = "يستخدم تصحيح ADB لتغيير إعدادات النظام.\nيعمل مباشرة على الجهاز بدون حاسوب.",
    shutterOff = "صوت الغالق مغلق",
    shutterOn = "صوت الغالق مفعّل",
    shutterOffDesc = "صوت غالق الكاميرا معطّل",
    shutterOnDesc = "صوت غالق الكاميرا مفعّل",
    turnOnShutter = "تشغيل صوت الغالق",
    turnOffShutter = "إيقاف صوت الغالق",
    mainFooter = "يغيّر إعدادات النظام باستخدام ADB المحلي.\nلا حاجة لحاسوب أو اتصال USB.",
    errorTitle = "خطأ",
    retry = "إعادة المحاولة",
    msgStartingAdb = "جارٍ تشغيل خادم ADB...",
    msgEnterPairingInfo = "يرجى إدخال منفذ ورمز الإقران",
    msgPairing = "جارٍ الإقران...",
    msgPairingSuccess = "تم الإقران! جارٍ الاتصال...",
    msgPairingFailed = { e -> "فشل الإقران: ${e ?: "خطأ غير معروف"}" },
    msgEnterDebugPort = "يرجى إدخال منفذ التصحيح اللاسلكي",
    msgConnecting = "جارٍ الاتصال...",
    msgConnectFailed = { e -> "فشل الاتصال: ${e ?: "لم يتم العثور على الجهاز"}" },
    msgDeviceNotFound = "لم يتم العثور على الجهاز",
    msgNotSupported = "هذا الجهاز لا يدعم إعدادات صوت الغالق.\nمتاح فقط على أجهزة Samsung Galaxy المباعة في كوريا.",
    msgCannotReadShutter = { e -> "تعذّر قراءة حالة صوت الغالق: $e" },
    msgSettingChangeFailed = { e -> "فشل تغيير الإعداد: ${e ?: ""}" },
    msgPairingTimeout = "انتهت مهلة الإقران",
    onboardingSubtitle = "دليل الإعداد",
    previous = "السابق",
    next = "التالي",
    getStarted = "ابدأ",
    onboardingStep1Title = "تفعيل خيارات المطور",
    onboardingStep1Items = listOf(
        "انتقل إلى الإعدادات > حول الهاتف > معلومات البرنامج",
        "انقر على 'رقم البناء' 7 مرات متتالية",
        "ستظهر رسالة \"تم تفعيل وضع المطور\"",
        "ارجع للإعدادات — ستظهر 'خيارات المطور' في الأسفل",
    ),
    onboardingStep2Title = "تشغيل تصحيح USB",
    onboardingStep2Items = listOf(
        "انتقل إلى الإعدادات > خيارات المطور",
        "قم بتشغيل 'تصحيح USB'",
        "إذا كان تصحيح USB رماديًا:\n  انتقل إلى الإعدادات > الأمان والخصوصية > الحظر التلقائي\n  وقم بإيقافه (أجهزة Samsung)",
    ),
    onboardingStep3Title = "تشغيل التصحيح اللاسلكي",
    onboardingStep3Items = listOf(
        "انتقل إلى الإعدادات > خيارات المطور > التصحيح اللاسلكي",
        "قم بتشغيل التصحيح اللاسلكي",
        "يجب أن تكون متصلاً بشبكة Wi-Fi",
        "لاحظ رقم المنفذ في أعلى الشاشة\n  (مثال: 44689 من 172.30.1.22:44689)",
    ),
    onboardingStep4Title = "إقران الجهاز",
    onboardingStep4Items = listOf(
        "مهم: استخدم تقسيم الشاشة لإبقاء الإعدادات\nوهذا التطبيق مفتوحين في نفس الوقت!",
        "انقر على 'إقران الجهاز برمز الإقران' في الإعدادات",
        "أدخل القيم الثلاث من النافذة المنبثقة:\n  ① منفذ الاتصال: من التصحيح اللاسلكي\n     (مثال: 44689)\n  ② منفذ الإقران: من النافذة المنبثقة\n     (مثال: 43641، مختلف عن أعلاه!)\n  ③ رمز الإقران: رقم مكون من 6 أرقام",
        "لا تغلق النافذة المنبثقة! انقر على\n'إقران واتصال' فورًا بعد الإدخال",
    ),
    onboardingStep5Title = "إيقاف صوت الغالق",
    onboardingStep5Items = listOf(
        "بعد الاتصال، ستظهر شاشة التحكم في صوت الغالق",
        "تبديل صوت الغالق بنقرة واحدة",
        "يُطبّق على تطبيق الكاميرا الافتراضي",
        "لا حاجة لحاسوب أو كابل USB!",
    ),
)

private fun simplifiedChineseStrings() = Strings(
    subtitle = "相机快门声控制",
    connectingChecking = "正在检查连接...",
    wirelessDebugSetup = "无线调试设置",
    splitScreenHint = "请使用分屏模式同时打开设置和本应用。",
    step1Label = "步骤 1. 无线调试页面顶部的端口",
    connectPortLabel = "连接端口",
    connectPortPlaceholder = "例: 44689",
    step2Label = "步骤 2. 点击「使用配对码配对设备」\n然后输入弹窗中的端口和配对码",
    pairingPortLabel = "配对弹窗的端口",
    pairingPortPlaceholder = "例: 37123（与上面不同！）",
    pairingCodeLabel = "配对码（6位数字）",
    pairingCodePlaceholder = "例: 482956",
    pairAndConnect = "配对并连接",
    pairingFooter = "使用ADB调试更改系统设置。\n无需电脑，直接在设备上运行。",
    shutterOff = "快门声已关闭",
    shutterOn = "快门声已开启",
    shutterOffDesc = "相机快门声已禁用",
    shutterOnDesc = "相机快门声已启用",
    turnOnShutter = "开启快门声",
    turnOffShutter = "关闭快门声",
    mainFooter = "使用本地ADB更改系统设置。\n无需电脑或USB连接。",
    errorTitle = "错误",
    retry = "重试",
    msgStartingAdb = "正在启动ADB服务器...",
    msgEnterPairingInfo = "请输入配对端口和配对码",
    msgPairing = "正在配对...",
    msgPairingSuccess = "配对成功！正在连接...",
    msgPairingFailed = { e -> "配对失败: ${e ?: "未知错误"}" },
    msgEnterDebugPort = "请输入无线调试端口",
    msgConnecting = "正在连接...",
    msgConnectFailed = { e -> "连接失败: ${e ?: "未找到设备"}" },
    msgDeviceNotFound = "未找到设备",
    msgNotSupported = "此设备不支持快门声设置。\n仅适用于在韩国销售的三星Galaxy设备。",
    msgCannotReadShutter = { e -> "无法读取快门声状态: $e" },
    msgSettingChangeFailed = { e -> "更改设置失败: ${e ?: ""}" },
    msgPairingTimeout = "配对超时",
    onboardingSubtitle = "设置指南",
    previous = "上一步",
    next = "下一步",
    getStarted = "开始使用",
    onboardingStep1Title = "启用开发者选项",
    onboardingStep1Items = listOf(
        "进入 设置 > 关于手机 > 软件信息",
        "连续点击「版本号」7次",
        "将显示\"已启用开发者模式\"消息",
        "返回设置主页，底部将出现「开发者选项」",
    ),
    onboardingStep2Title = "打开USB调试",
    onboardingStep2Items = listOf(
        "进入 设置 > 开发者选项",
        "打开「USB调试」",
        "如果USB调试为灰色：\n  进入 设置 > 安全和隐私 > 自动拦截\n  将其关闭（三星设备）",
    ),
    onboardingStep3Title = "打开无线调试",
    onboardingStep3Items = listOf(
        "进入 设置 > 开发者选项 > 无线调试",
        "打开无线调试",
        "必须连接Wi-Fi",
        "记住页面顶部显示的端口号\n  （例: 172.30.1.22:44689 中的 44689）",
    ),
    onboardingStep4Title = "配对设备",
    onboardingStep4Items = listOf(
        "重要：请使用分屏模式同时打开\n设置和本应用！",
        "在设置中点击「使用配对码配对设备」",
        "将弹窗中的3个值输入应用：\n  ① 连接端口：无线调试页面的端口\n     （例: 44689）\n  ② 配对端口：弹窗中的端口\n     （例: 43641，与连接端口不同！）\n  ③ 配对码：弹窗中的6位数字",
        "不要关闭弹窗！输入后立即点击\n「配对并连接」按钮",
    ),
    onboardingStep5Title = "关闭快门声",
    onboardingStep5Items = listOf(
        "连接完成后，将显示快门声控制界面",
        "一键切换快门声的开关",
        "即时应用到默认相机应用",
        "无需电脑或USB线！",
    ),
)

private fun traditionalChineseStrings() = Strings(
    subtitle = "相機快門聲控制",
    connectingChecking = "正在檢查連線...",
    wirelessDebugSetup = "無線偵錯設定",
    splitScreenHint = "請使用分割畫面同時開啟設定和本應用程式。",
    step1Label = "步驟 1. 無線偵錯畫面頂部的連接埠",
    connectPortLabel = "連線連接埠",
    connectPortPlaceholder = "例: 44689",
    step2Label = "步驟 2. 點選「使用配對碼配對裝置」\n然後輸入彈出視窗中的連接埠和配對碼",
    pairingPortLabel = "配對彈出視窗的連接埠",
    pairingPortPlaceholder = "例: 37123（與上方不同！）",
    pairingCodeLabel = "配對碼（6位數字）",
    pairingCodePlaceholder = "例: 482956",
    pairAndConnect = "配對並連線",
    pairingFooter = "使用ADB偵錯變更系統設定。\n無需電腦，直接在裝置上運作。",
    shutterOff = "快門聲已關閉",
    shutterOn = "快門聲已開啟",
    shutterOffDesc = "相機快門聲已停用",
    shutterOnDesc = "相機快門聲已啟用",
    turnOnShutter = "開啟快門聲",
    turnOffShutter = "關閉快門聲",
    mainFooter = "使用本機ADB變更系統設定。\n無需電腦或USB連線。",
    errorTitle = "錯誤",
    retry = "重試",
    msgStartingAdb = "正在啟動ADB伺服器...",
    msgEnterPairingInfo = "請輸入配對連接埠和配對碼",
    msgPairing = "正在配對...",
    msgPairingSuccess = "配對成功！正在連線...",
    msgPairingFailed = { e -> "配對失敗: ${e ?: "未知錯誤"}" },
    msgEnterDebugPort = "請輸入無線偵錯連接埠",
    msgConnecting = "正在連線...",
    msgConnectFailed = { e -> "連線失敗: ${e ?: "找不到裝置"}" },
    msgDeviceNotFound = "找不到裝置",
    msgNotSupported = "此裝置不支援快門聲設定。\n僅適用於在韓國銷售的三星Galaxy裝置。",
    msgCannotReadShutter = { e -> "無法讀取快門聲狀態: $e" },
    msgSettingChangeFailed = { e -> "變更設定失敗: ${e ?: ""}" },
    msgPairingTimeout = "配對逾時",
    onboardingSubtitle = "設定指南",
    previous = "上一步",
    next = "下一步",
    getStarted = "開始使用",
    onboardingStep1Title = "啟用開發人員選項",
    onboardingStep1Items = listOf(
        "前往 設定 > 關於手機 > 軟體資訊",
        "連續點擊「版本號碼」7次",
        "將顯示「已啟用開發人員模式」訊息",
        "返回設定主頁，底部將出現「開發人員選項」",
    ),
    onboardingStep2Title = "開啟USB偵錯",
    onboardingStep2Items = listOf(
        "前往 設定 > 開發人員選項",
        "開啟「USB偵錯」",
        "若USB偵錯為灰色：\n  前往 設定 > 安全性與隱私 > 自動封鎖\n  將其關閉（三星裝置）",
    ),
    onboardingStep3Title = "開啟無線偵錯",
    onboardingStep3Items = listOf(
        "前往 設定 > 開發人員選項 > 無線偵錯",
        "開啟無線偵錯",
        "必須連接Wi-Fi",
        "記住畫面頂部顯示的連接埠號碼\n  （例: 172.30.1.22:44689 中的 44689）",
    ),
    onboardingStep4Title = "配對裝置",
    onboardingStep4Items = listOf(
        "重要：請使用分割畫面同時開啟\n設定和本應用程式！",
        "在設定中點選「使用配對碼配對裝置」",
        "將彈出視窗中的3個值輸入應用程式：\n  ① 連線連接埠：無線偵錯畫面的連接埠\n     （例: 44689）\n  ② 配對連接埠：彈出視窗中的連接埠\n     （例: 43641，與連線連接埠不同！）\n  ③ 配對碼：彈出視窗中的6位數字",
        "不要關閉彈出視窗！輸入後立即點選\n「配對並連線」按鈕",
    ),
    onboardingStep5Title = "關閉快門聲",
    onboardingStep5Items = listOf(
        "連線完成後，將顯示快門聲控制畫面",
        "一鍵切換快門聲的開關",
        "即時套用到預設相機應用程式",
        "無需電腦或USB線！",
    ),
)
